from .mpl_widget import MplWidget
from .dataframe_plot_widget import DataFramePlotWidget
from .time_series_data_plot_widget import TimeSeriesDataPlotWidget
from .histogram_plot_widget import HistogramPlotWidget